### PR TITLE
Production readiness

### PR DESCRIPTION
**Pull request by uromahn**
This PR contains multiple changes:
* ability to specify a set of languages for the expand endpoint
* renamed endpoints to be consistent:
  * `/parser` -> `/parse`
  * `/expandparser` -> `/expandparse`
* added proper logging with zerolog and made the logger output configurable (structured <--> pretty-print)
* instrumented service with Prometheus client library to be able to emit metrics (see README.md)
* updated README.md to document environment variables.

NOTE: if the renamed endpoints would cause compatibility issues with existing clients, I can revert them back.
Please mention that in a comment.

### CODE REVIEW

**Comment by johnlonganecker** [comment]
Hey @uromahn! thanks for this PR, it will take me a little time to make the time to review this, but an initial skim it all looks good and I appreciate the new features this brings!

**Comment by johnlonganecker** [comment]
The addition of logs and metrics is a great addition. Looking back I do think omitting the `r` from the endpoints does make more sense.

I would like to keep the endpoints the same just so that it is backwards compatible for others using this. If you want to make an alias for this `non-r` endpoints I am fine with that. For example have the `non-r` endpoint function call the endpoints that end in `r`

Could you also add some new examples of using your new language option to the README file?

**Comment by uromahn** [comment]
@johnlonganecker I will revert the endpoint names to the original ones. I had a similar concern that backward compatibility might be more important than better naming.
I will also extend the README with the new examples.
Updated PR coming soon...

**Comment by uromahn** [comment]
@johnlonganecker updated the branch to reflect your comments. Please take another look. Thanks!

**Comment by uromahn** [comment]
Oh, wait a second. Forgot to add my changes to the README. Will update that soon.

**Comment by johnlonganecker** [comment]
Thanks @uromahn I will review your PR either today or tomorrow. With just some skimming it is looking good! Thanks again.

**Comment by uliromahn** [comment]
@johnlonganecker ping ... :)
Any chance you can find some time to go over this PR?

Thank you!

**Comment by johnlonganecker** [comment]
Hey @uromahn, I will try and take a look at it tonight. Life has been pretty busy. I appreciate you checking in!

**Comment by johnlonganecker** [comment]
Everything looks functionally great! can you update the readme examples to use <host> instead of localhost? After that I will accept the PR.

Thanks for your help and patience!

**Comment by uromahn** [comment]
Wow, good catch! Typical "copy & paste error".
Should be fixed now.

**Comment by johnlonganecker** [comment]
Looks good, thanks for your addition @uromahn!

**Pull request merged**
